// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ooqshqbvcujsysevvklx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vcXNocWJ2Y3Vqc3lzZXZ2a2x4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMjc1NjEsImV4cCI6MjA3NDYwMzU2MX0.RBSLu7HD7uSY_xknV-q0sXWreXkIAv6QhfVUeG4jKnI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});